artifacts_root:artifacts

data_ingestion:
  root_dir:artifacts/data_ingestion
  source_URL:https://github.com/kumar7ashutosh/kumar7ashutosh/raw/refs/heads/main/summarizer-data.zip
  local_data_file:artifacts/data_ingestion/data.zip
  unzip_dir:artifacts/data_ingestion